name: ${{values.app_name}}-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ '${{ vars.DOCKERHUB_USERNAME }}' }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}'
      -
        name: set commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: limbuhimal/${{values.app_name}}:${{ '${{ env.COMMIT_ID }}' }}'
    outputs:
      commit_id: ${{ '${{ env.COMMIT_ID }}' }}'

  cd:
    runs-on: self-hosted
    needs: ci
    steps:
      - uses: actions/checkout@v3

      - name: Modify value file
        shell: bash
        run: |
          echo ${{ '${{ needs.ci.outputs.commit_id }}' }}
          sudo apt update
          sudo apt install -y yq
          yq -Yi '.image.tag = "${{ '${{ needs.ci.outputs.commit_id }}' }}"' charts/${{values.app_name}}/values-${{values.app_env}}.yaml
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit ${{ '${{ needs.ci.outputs.commit_id }}' }}'
      - name: Install ArgoCD CLI
        shell: bash
        run: |
          curl -ksSL -o argocd argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
      - name: Argo CD Login
        shell: bash
        run: |
          argocd login argocd-server.argocd.svc.cluster.local:80 \
          --username admin \
          --grpc-web \
          --plaintext \
          --password ${{ '${{ secrets.ARGOCD_PW }}' }}
      - name: Ensure argocd repo and add
        shell: bash
        run: |
          repo="https://github.com/limbuhimal-1/${{values.app_name}}.git"

        # connects the argocd repo  
          argocd repo list | grep -q $repo || argocd repo add $repo

        # creates the argocd repo
          argocd app get ${{values.app_name}} || argocd app create ${{values.app_name}} \
            --repo $repo \
            --path charts/${{values.app_name}} \
            --dest-namespace ${{values.app_env}} \
            --dest-server https://kubernetes.default.svc \
            --values values-${{values.app_env}}.yaml \
            --revision master \
            --sync-policy manual \
            --sync-option CreateNamespace=true

      - name: Sync Application
        shell: bash
        run: |
          argocd app sync ${{values.app_name}}
          argocd app wait $app_to_sync --timeout 180
      